### PR TITLE
fix(package): update npm files field for new server bundle

### LINKED ISSUE #637: Last release (v0.39.8) missing boardgame.io/server package
I was trying to upgrade FBG to v0.39.8 but it seems like it is missing the server package:

```
Error: Cannot find module 'boardgame.io/server'
```
on https://github.com/freeboardgames/FreeBoardGames.org/blob/7e26b4125fe3f9722b54d4479c11606fc52739f5/server/bgio.ts#L4

 it does indeed seem to be missing from `node_modules`:
```
flamecoals@flamecoals-desktop:~/playground/FreeBoardGames.org$ ls node_modules/boardgame.io/
ai  client  core  debug  dist  internal  LICENSE  master  multiplayer  node_modules  package.json  plugins  react  react-native  README.md
```

but the tutorial still says to import this module:
https://boardgame.io/documentation/#/multiplayer?id=setting-up-the-server

It was working fine on v0.39.4

### PR DESCRIPTION
**Pull request by delucis**
Fixes #637

- The `./server.js` proxy was replaced by the `./server` proxy package
- The build at `./dist/server.js` was moved to `./dist/cjs/server.js`, which is covered already by including `dist/cjs` in `files`

### CODE REVIEW

**Comment by nicolodavis** [comment]
Released.
