### ISSUE TITLE
Last release (v0.39.8) missing boardgame.io/server package

### ISSUE THREAD

**Issue by flamecoals** [nicolodavis/boardgame.io#637]
I was trying to upgrade FBG to v0.39.8 but it seems like it is missing the server package:

```
Error: Cannot find module 'boardgame.io/server'
```
on https://github.com/freeboardgames/FreeBoardGames.org/blob/7e26b4125fe3f9722b54d4479c11606fc52739f5/server/bgio.ts#L4

 it does indeed seem to be missing from `node_modules`:
```
flamecoals@flamecoals-desktop:~/playground/FreeBoardGames.org$ ls node_modules/boardgame.io/
ai  client  core  debug  dist  internal  LICENSE  master  multiplayer  node_modules  package.json  plugins  react  react-native  README.md
```

but the tutorial still says to import this module:
https://boardgame.io/documentation/#/multiplayer?id=setting-up-the-server

It was working fine on v0.39.4

**Comment by delucis** [comment]
I tweaked how the server was bundled in #622 and it looked like it was working in my machine, but I’m just realising that I didn’t update `files` in package.json, so the server wasn’t included on release. Thanks for opening this!
