### ISSUE TITLE
Trouble testing feature in separate project

### ISSUE THREAD

**Issue by joepinion** [nicolodavis/boardgame.io#575]
I'm sure there's just something basic that I don't understand about npm, rollup, etc, but would greatly appreciate the help. I wrote some code for a new feature and can get it to work fine in boardgame.io itself (ie the examples etc).

Trying to run a local and/or my forked version of boardgame.io in my personal project. So in dependencies, something like
`"boardgame.io": "file:/Users/username/boardgame.io",
`But on npm install, I get stuck on
`> boardgame.io@0.38.1 build /Users/josephellis/.npm/_cacache/tmp/git-clone-1fdbc7c2
> cross-env BABEL_ENV=rollup rollup --config rollup.config.js

[!] Error: Cannot find module 'rollup-plugin-node-resolve'
Require stack:
- /Users/josephellis/.npm/_cacache/tmp/git-clone-1fdbc7c2/rollup.config.js
- /usr/local/lib/node_modules/rollup/dist/bin/rollup
Error: Cannot find module 'rollup-plugin-node-resolve'
Require stack:
- /Users/josephellis/.npm/_cacache/tmp/git-clone-1fdbc7c2/rollup.config.js
- /usr/local/lib/node_modules/rollup/dist/bin/rollup
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/Users/josephellis/.npm/_cacache/tmp/git-clone-1fdbc7c2/rollup.config.js:7:31)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.require.extensions.<computed> [as .js] (/usr/local/lib/node_modules/rollup/dist/bin/rollup:1857:24)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)`

If I move all the rollup dependencies in my local copy of boardgame.io to be regular dependencies, it installs, but then I try to run a client and I get:
`Module not found: Can't resolve 'boardgame.io/core' in '/Users/username/project-name/src/game'`

So there's either something very basic I'm missing about npm, or something very basic I'm missing about requirements to develop on this project. Any insight?? Would be happy to feel dumb (or more likely, my inexperience showing) with the solution.

**Comment by delucis** [comment]
The boardgame.io you download from npm exposes the bundled files compiled by rollup. To test out your fork locally, I’ve found the easiest way is to use [`npm link`](https://docs.npmjs.com/cli/link) to “install” your fork in your local project. This actually just creates a symlink in `node_modules` to your fork rather than installing like a normal dependency.

Then you can run `npm build` in your fork to make sure it exposes all the correct bindings.

**Comment by joepinion** [comment]
It seems like that helps with the build. npm link, npm build works. But actually trying to run the server or client in my project still results in 
`Error: Cannot find module 'boardgame.io/core'`
in the server and
`Module not found: Can't resolve 'boardgame.io/core' in '/Users/username/project/src/game'`
in the client.

This project works fine with the official "^0.37.2" verison of boardgame-io in package.json installed via npm.

The dist folder is built in the local clone of my fork, including boardgame.io, etc. I also tried just boardgame.io master branch local clone, and even 0.37.2 local clone, since that's the first version I had ever used. All with the problem above.

Once again, I'm sure I'm missing something a novice would miss. Is there a global package it expects me to have installed? Some kind of cache to clear? Something like that?

**Comment by jasonharrison** [comment]
@joepinion In the boardgame.io directory, run `npm run prepack`.  It should then work for you :-)

The reason is because we create aliases for `boardgame.io/core` etc.

**Comment by joepinion** [comment]
YES. thank you.

**Comment by nicolodavis** [comment]
Also, just wanted to point out that both `npm link` as well as `npm install /path/to/local/package` create symlinks (i.e. neither really "installs" the package in `node_modules`).  This has some nice properties like being able to modify the `boardgame.io` code and seeing it instantly reflect the changes in the dependent package after you run `npm run prepack`.
